module.exports = {
    rolesPermission: [
        "Gym Leader - Water",
        "Gym Leader - Fire",
        "Gym Leader - Grass",
        "Gym Leader - Ice",
        "Gym Leader - Fairy",
        "Gym Leader - Psychic",
        "Gym Leader - Ghost",
        "Gym Leader - Poison",
        "Gym Leader - Steel",
        "Gym Leader - Dark",
        "Gym Leader - Ground",
        "Gym Leader - Normal",
        "Gym Leader - Flying",
        "Gym Leader - Bug",
        "Gym Leader - Electric",
        "Gym Leader - Fighting",
        "Gym Leader - Dragon",
        "Gym Leader - Rock"
    ],
    listTypes: [
        'water',
        'fire',
        'grass',
        'ice',
        'fairy',
        'psychic',
        'ghost',
        'poison',
        'steel',
        'dark',
        'ground',
        'normal',
        'flying',
        'bug',
        'electric',
        'fighting',
        'dragon',
        'rock'
    ]
};